### ISSUE TITLE
Add Unit Tests for Text Extraction Functions

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/VetsAI#2]
Testing Framework: Use a testing framework like ```unittest``` or ```pytest``` to create unit tests for the text extraction functions.
  • Coverage: Write tests for various scenarios, including:
  • Valid PDF and DOCX files.
  • Empty documents.
  • Documents with non-text content (images, charts).
  • Files with special characters and different encodings.
  • Continuous Integration: Integrate the tests into the CI pipeline to ensure they run automatically on code changes.

Relevant Code Sections:

  • ```extract_text_from_pdf(file)```
  • ```extract_text_from_word(file)```

Acceptance Criteria:

1. Unit tests should be created using ```unittest``` or ```pytest```.
2. Tests should cover all outlined scenarios (valid files, empty files, non-text content, special characters, etc.).
3. Tests should be integrated with the CI pipeline and run automatically on every code push.
4. Code coverage should increase with the addition of these tests.

Technical Considerations:

• Use ```unittest``` or ```pytest``` for testing.
• Mock file handling where necessary to simulate different scenarios.
• Ensure that test dependencies are properly configured in the CI pipeline.

**Comment by Shizu-ka** [comment]
will work on this, assign this to me

**Comment by jeromehardaway** [comment]
@Shizu-ka I am going to give first right to refusal to my troops then I will assign to you if no one takes it.

**Comment by jonulak** [comment]
I can work on this if it's still available

**Comment by jeromehardaway** [comment]
@jonulak go for it.

**Comment by jonulak** [comment]
Unit tests are looking good, but I'll need access to git actions to implement automated tests.
