### ISSUE TITLE
Separate job code loading from app.py

### ISSUE THREAD

**Issue by jonulak** [Vets-Who-Code/VetsAI#20]
## Data Loading Refactor: Extract Data Loading Logic from app.py

**Type**: Refactor  
**Priority**: Medium  

### Description
Move data loading logic from `app.py` into a dedicated module to improve code organization and maintain separation of concerns.

### Current State
- Data loading logic for MOS data and VWC path mapping is currently located in `app.py`
- This violates separation of concerns and makes the main application file more complex than necessary

### Required Changes
1. Create new file `data/data_loader.py`
2. Extract data loading functions from `app.py` into `data_loader.py`
3. Update `app.py` to import the necessary functions from `data_loader`
4. Run existing test suite to verify data loading functionality remains intact

### Files Affected
- `app.py` (modify)
- `data/data_loader.py` (create)

### Acceptance Criteria
- [ ] All data loading logic moved to `data_loader.py`
- [ ] `app.py` imports and uses functions from `data_loader`
- [ ] All existing tests pass
- [ ] No changes to current data loading behavior

**Comment by jeromehardaway** [comment]
Consider adding these changes:

## Data Loading Refactor: Extract Data Loading Logic from app.py

**Type**: Refactor  
**Priority**: Medium  

### Description
Move data loading logic from `app.py` into a dedicated module to improve code organization and maintain separation of concerns.

### Current State
- Data loading logic for MOS data and VWC path mapping is currently located in `app.py`
- This violates separation of concerns and makes the main application file more complex than necessary

### Required Changes
1. Create new file `data/data_loader.py`
2. Extract data loading functions from `app.py` into `data_loader.py`
3. Update `app.py` to import the necessary functions from `data_loader`
4. Run existing test suite to verify data loading functionality remains intact

### Files Affected
- `app.py` (modify)
- `data/data_loader.py` (create)

### Acceptance Criteria
- [ ] All data loading logic moved to `data_loader.py`
- [ ] `app.py` imports and uses functions from `data_loader`
- [ ] All existing tests pass
- [ ] No changes to current data loading behavior
